# Generated by Django 6.0 on 2025-12-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo_profile', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
